AllCops:
    Exclude:
        - lib/prometheus/client/version.rb

AlignHash:
    EnforcedHashRocketStyle: table

Style/TrailingCommaInArguments:
    EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma

Metrics/AbcSize:
    Max: 18

Style/GuardClause:
  Enabled: false